# Generated by Django 5.1.15 on 2026-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_orderlineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='cost_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
