# Generated by Django 5.1.15 on 2026-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_orderlineitem_cost_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online (store QR)'), ('UPI', 'UPI (pay link)')], default='CASH', max_length=10),
        ),
    ]
