# Generated by Django 5.1.15 on 2026-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_business_order_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
