# Generated by Django 5.1.15 on 2026-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='UPI ID'),
        ),
    ]
